Vhnaged 4th flow

diff --git a/.github/workflows/4-build&push-image.yml b/.github/workflows/4-build&push-image.yml
--- a/.github/workflows/4-build&push-image.yml
+++ b/.github/workflows/4-build&push-image.yml
@@ -141,13 +141,24 @@ jobs:
 
       - name: Login to Argo CD
         run: |
-          argocd login $ARGOCD_SERVER --username admin --password $ARGOCD_AUTH_TOKEN
+          echo "=== 🔹 Logging in to ArgoCD ==="
+          argocd login $ARGOCD_SERVER --username admin --password $ARGOCD_ADMIN_PASSWORD --grpc-web || {
+            echo "ERROR---XXX: ArgoCD login failed"; exit 1;
+          }
+          echo "Correct--------> Successfully logged in to ArgoCD."
+
         env:
-          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
-          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
+          ARGOCD_SERVER: argocd.trialphase.shop
+          ARGOCD_ADMIN_PASSWORD: ${{ secrets.ARGOCD_ADMIN_PASSWORD }}
+
 
       - name: Sync Argo CD Application
         run: |
-          argocd app sync $ARGOCD_APP_NAME
+          echo "===  Starting ArgoCD sync for app: $ARGOCD_APP_NAME ==="
+          argocd app get $ARGOCD_APP_NAME || echo " PROBLEM--> App not found yet, continuing..."
+          argocd app sync $ARGOCD_APP_NAME || {
+            echo "ERROR---XXX: Sync failed for app: $ARGOCD_APP_NAME"; exit 1;
+          }
+          echo "Correct--------> ArgoCD sync completed successfully."
         env:
           ARGOCD_APP_NAME: currencyconverter-production
