Vhnaged 4th flow

diff --git a/.github/workflows/4-build&push-image.yml b/.github/workflows/4-build&push-image.yml
--- a/.github/workflows/4-build&push-image.yml
+++ b/.github/workflows/4-build&push-image.yml
@@ -144,19 +144,19 @@ jobs:
           echo "=== 🔹 Logging in to ArgoCD ==="
           rm -rf ~/.argocd
 
-          if [ -z "$ARGOCD_ADMIN_PASSWORD" ]; then
-            echo "❌ ERROR: ARGOCD_ADMIN_PASSWORD is empty!"
+          if [ -z "$ARGOCD_AUTH_TOKEN" ]; then
+            echo "❌ ERROR: ARGOCD_AUTH_TOKEN is empty!"
             exit 1
           fi
 
-          argocd login $ARGOCD_SERVER --username admin --password "$ARGOCD_ADMIN_PASSWORD" --grpc-web --insecure || {
+          argocd login $ARGOCD_SERVER --username admin --password "$ARGOCD_AUTH_TOKEN" --grpc-web --insecure || {
             echo "❌ ERROR: ArgoCD login failed"; exit 1;
           }
 
           echo "✅ Successfully logged in to ArgoCD."
         env:
           ARGOCD_SERVER: argocd.trialphase.shop
-          ARGOCD_ADMIN_PASSWORD: ${{ secrets.ARGOCD_ADMIN_PASSWORD }}
+          ARGOCD_ADMIN_PASSWORD: ${{ secrets.ARGOCD_AUTH_TOKEN }}
 
 
 
